# site properties and page defaults
title: Luo Lab
subtitle: 
description: Our lab develops innovative computational approaches to understand complex biological systems and improve human health. We focus on integrating multi-omics and clinical data with state-of-the-art machine learning to enable earlier diagnosis, personalized treatment, and deeper biological insights. By combining rigorous data science with close collaboration across disciplines, we aim to translate discoveries into real-world impact.
header: images/background1.png
footer: images/background.jpg
proofer: false

# site social media and other links
links:
  email: ping.luo@algomau.ca
  orcid: 0000-0002-0039-747X
  google-scholar: 7iAJBfkAAAAJ&hl=en
  github: luoping1004
  twitter: 
  # youtube: "@ping-algoma"

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
